apiVersion: v1
kind: Service
metadata:
  name: microservice3-service
spec:
  selector:
    app: microservice3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30003
  type: NodePort