apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: coin-flip-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice5
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: ratio_heads_to_tails
      targetAverageValue: 2.0
