apiVersion: v1
kind: Service
metadata:
  name: microservice5-service
spec:
  selector:
    app: microservice5
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30005
  type: NodePort